//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Activitée
{
	private int numjour
	{
		get;
		set;
	}

	private int heuredeb
	{
		get;
		set;
	}

	private int heurefin
	{
		get;
		set;
	}

	private string libelle
	{
		get;
		set;
	}

	private List<Astronaute> patipants
	{
		get;
		set;
	}

	private object catégorie
	{
		get;
		set;
	}

	public virtual IEnumerable<Astronautes> Astronautes
	{
		get;
		set;
	}

	public virtual IEnumerable<Lieu> Lieu
	{
		get;
		set;
	}

}

