//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class carte
{
	private int image
	{
		get;
		set;
	}

	private lieu origine
	{
		get;
		set;
	}

	private int echelle
	{
		get;
		set;
	}

	public virtual IEnumerable<Lieu> Lieu
	{
		get;
		set;
	}

}

