//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Jour
{
	private int num
	{
		get;
		set;
	}

	private List<Activitée> activitées
	{
		get;
		set;
	}

	public virtual IEnumerable<Activitée> Activitée
	{
		get;
		set;
	}

}

