//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Mission
{
	private int Duree
	{
		get;
		set;
	}

	private string nom
	{
		get;
		set;
	}

	private carte Emplacement
	{
		get;
		set;
	}

	public virtual IEnumerable<Jour> Jour
	{
		get;
		set;
	}

}

